# Generated by Django 5.0.3 on 2026-04-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='drug_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
