# Generated by Django 5.0.3 on 2026-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('APPOINTMENT', 'Appointment'), ('DIAGNOSIS', 'Diagnosis'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
